import type { WeddingConfig } from "../../types";

export const nithinTejuWedding: WeddingConfig = {
  slug: "nithin-teju",
  couple: {
    partnerOne: "Nithin",
    partnerTwo: "Tejaswini",
    displayNames: "Nithin & Tejaswini",
    tagline: "Join us as we celebrate the beginning of forever.",
    story:
      "From meeting in college nearly a decade ago to growing together through every chapter since, our story has been built on friendship, laughter, and shared dreams. This weekend is a celebration of all of it.",
    heroTitle: "#IntheLife",
    portmanteau: {
      text: "nithIN + THEjaswini",
      segments: [
        { text: "nith", isPrimary: true },
        { text: "IN", isPrimary: false },
        { text: " + ", isPrimary: true },
        { text: "THE", isPrimary: false },
        { text: "jaswini", isPrimary: true },
      ],
    },
  },
  weddingDate: "2026-08-29T09:30:00-04:00",
  timeZone: "America/New_York",
  heroImage: "/weddings/nithin-teju/gallery/official_opener.png",
  theme: {
    name: "rose",
  },
  accent: "#b24b5a",
  invitation: {
    greeting: "Our next chapter begins.",
    message:
      "Come celebrate with us through cherished traditions, joyful moments, and unforgettable memories.",
  },
  entryInvitation: {
    enabled: true,
    eyebrow: "A celebration awaits",
    message: "Together with their families, invite you to celebrate their wedding.",
    openLabel: "Open Invitation",
    backgroundImage: "/weddings/nithin-teju/gallery/official_opener.png",
    rememberForSession: false,
  },
  music: {
    src: "/weddings/nithin-teju/gallery/song.mp3",
    title: "Sample wedding music",
    loop: true,
    volume: 0.55,
  },
  events: [
    {
      id: "haldi",
      title: "Haldi Carnival",
      type: "Haldi",
      date: "2026-08-27",
      startTime: "17:00",
      dressCode: "Biege, Yellow, or Florals",
      note: "Expect Turmeric, Games, Laughter, and Sunlight.",
      image: "/weddings/nithin-teju/gallery/haldi_portrait.png",
      venue: {
        name: "Address here",
        address: "Address here",
        city: "Cumming, GA",
        mapQuery: "Address here",
      },
    },
    {
      id: "mehendi",
      title: "Mehendi",
      type: "Mehendi",
      date: "2026-08-28",
      startTime: "15:00",
      dressCode: "Comfortable wear",
      note: "Henna, Music, Gossip and Pictures.",
      image: "/weddings/nithin-teju/gallery/mehendi_portrait_2.png",
      venue: {
        name: "Address here",
        address: "Address here",
        city: "Cumming, GA",
        mapQuery: "Address here",
      },
    },
    {
      id: "wedding",
      title: "Wedding Ceremony",
      type: "Wedding",
      date: "2026-08-29",
      startTime: "08:00",
      endTime: "12:30",
      dressCode: "Traditional Indian Attire",
      note: "Please be as early as possible to witness the entire ceremony and bless us during the sacred moment. Breakfast will be served.",
      image: "/weddings/nithin-teju/gallery/wedding_portrait.jpeg",
      venue: {
        name: "Reflections Event Space",
        address: "215 Advantage Dr Suite 100",
        city: "Cumming, GA",
        mapQuery: "Reflections Event Space, 215 Advantage Drive Suite 100, Cumming, GA 30040",
      },
    },
    {
      id: "reception",
      title: "Reception & Cocktail Party",
      type: "Reception & Cocktail",
      date: "2026-08-29",
      startTime: "19:00",
      endTime: "23:30",
      timeRanges: [
        { label: "Main Event", startTime: "19:00", endTime: "23:00" },
        { label: "After Party", startTime: "23:00", endTime: "01:00" },
      ],
      dressCode: "Men - Blazers / Tuxedos, Women - Cocktail wear",
      note: "Dinner, Cocktails and Dancing.",
      image: "/weddings/nithin-teju/gallery/cocktail_party_portrait_updated.jpeg",
      venue: {
        name: "Reflections Event Space",
        address: "215 Advantage Dr Suite 100",
        city: "Cumming, GA",
        mapQuery: "Reflections Event Space, 215 Advantage Drive Suite 100, Cumming, GA 30040",
      },
    },
  ],
  gallery: [
    {
      id: "houston-wedding-photo",
      type: "photo",
      title: "",
      src: "/weddings/nithin-teju/gallery/engagement-portrait.jpeg",
    },
    {
      id: "vermont",
      type: "photo",
      title: "",
      src: "/weddings/nithin-teju/gallery/memories_vermont.jpeg",
    },
    {
      id: "mendocino",
      type: "photo",
      title: "",
      src: "/weddings/nithin-teju/gallery/save-the-date-film.jpeg",
    },
    {
      id: "pandu_cocktail",
      type: "photo",
      title: "",
      src: "/weddings/nithin-teju/gallery/memories_pandu_cocktail.jpeg",
    },
    {
      id: "houston_cocktail",
      type: "photo",
      title: "",
      src: "/weddings/nithin-teju/gallery/memories_houston_cocktail_party.jpeg",
    },
  ],
  livestream: {
    title: "Wedding Ceremony Live",
    youtubeVideoId: "jfKfPfyJRdk",
    startsAt: "2026-08-29T09:30:00-04:00",
  },
  rsvp: {
    deadline: "2026-08-15",
    contactName: "Yash",
    contactPhone: "+1 469-996-4010",
    maxGuests: 4,
    googleFormUrl:
      "https://docs.google.com/forms/d/e/1FAIpQLSftaxwdHRtQc6H5BRk2DT9zWrbzeaowBzrMR6XAbpknZPauzA/viewform?usp=publish-editor",
    googleFormEmbedUrl:
      "https://docs.google.com/forms/d/e/1FAIpQLSftaxwdHRtQc6H5BRk2DT9zWrbzeaowBzrMR6XAbpknZPauzA/viewform?embedded=true",
    googleFormFieldIds: {
      fullName: "entry.280492329",
      phone: "entry.968995082",
      attendance: "entry.716561151",
      guests: "entry.625161931",
      guestNames: "entry.1401189441",
      events: "entry.801008396",
    },
    googleFormOptionLabels: {
      attendance: {
        yes: "Yes, I will attend",
        maybe: "Maybe",
        no: "Sorry, I cannot attend",
      },
      events: {
        haldi: "Haldi",
        mehendi: "Mehendi",
        wedding: "Wedding Ceremony",
        reception: "Reception & Cocktail Party",
      },
    },
  },
};
